name: Build & commit Dependabot changes

on:
  pull_request:

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-commit:
    name: Build & commit Dependabot changes
    if: github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.head.ref }}
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v6

      - name: Install dependencies
        run: npm ci

      - name: Build
        run: npm run build

      - name: Commit and push changes
        run: |
          git add .

          if git diff --cached --quiet; then
            echo "No changes to commit."
            exit 0
          fi

          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git commit -m "[dependabot skip] Update build artifacts"
          git push origin HEAD:${{ github.event.pull_request.head.ref }}
